logging:
  file: logs/cas/app.log
  level:
    root: INFO

cas:
  view:
    defaultRedirectUrl: https://localhost:20000/

server:
  ssl:
    key-store: classpath:keystore/thekeystore.jks
    key-store-password: changeit
    key-password: changeit