server:
  port: 10010

spring:
  mvc:
    locale: tr_TR

cas:
  adminPagesSecurity:
    ip: 127\.0\.0\.1
  ticket:
    tgt:
      rememberMe:
        enabled: true
  locale:
    defaultValue: tr
  authn:
    accept:
      users:
    rest:
      uri: https://localhost:10000/login/
      passwordEncoder:
        type: NONE